apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-ctr-app
  name: multi-ctr-app
spec:
  volumes:
  - name: emptydir-vol
    emptyDir: {}
  containers:
  - image: nginx
    name: ctr-1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: emptydir-vol
      mountPath: /app
  - name: ctr-2
    image: busybox
    command: ["sh", "-c", "sleep 5000"]
    volumeMounts:
    - name: emptydir-vol
      mountPath: /data
