apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-app
  name: web-app
spec:
  nodeName:  i-0f68a08663ec4e258
  volumes:
  - name: hp-volume
    hostPath:
      path: /pvdir
  containers:
  - image: nginx
    name: ctr-1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: hp-volume
      mountPath: /usr/share/nginx/html
